<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="NACTS-081729" name="ApiTest" tests="70" failures="50" timestamp="2 Nov 2016 14:36:47 GMT" time="10.266" errors="0">
  <testcase name="apiErrorAddressId" time="1.341" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorAddressId(ApiCustomerPost.java:198)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorAddressId -->
  <testcase name="apiErrorBlankAddress" time="0.078" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If address is provided, address1 is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If address is provided, address1 is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankAddress(ApiCustomerPost.java:210)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankAddress -->
  <testcase name="apiErrorBlankCity" time="0.032" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If address is provided, city is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If address is provided, city is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankCity(ApiCustomerPost.java:248)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankCity -->
  <testcase name="apiErrorBlankContact" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorBlankContactFirstName" time="0.031" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorBlankContactLastName" time="0.032" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorBlankContactName" time="0.031" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorBlankContactType" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorBlankCountry" time="0.046" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If address is provided, country is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If address is provided, country is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankCountry(ApiCustomerPost.java:272)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankCountry -->
  <testcase name="apiErrorBlankCustomerType" time="0.062" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorBlankEmail" time="0.015" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorBlankPassword" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Field is blank.] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Field is blank.] but found [null]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPassword(ApiCustomerPost.java:647)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPassword -->
  <testcase name="apiErrorBlankPersonalId" time="0.031" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If personal identifier info is provided, personal identifier is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If personal identifier info is provided, personal identifier is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPersonalId(ApiCustomerPost.java:534)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPersonalId -->
  <testcase name="apiErrorBlankPersonalIdType" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If personal identifier info is provided, personal identifier type is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If personal identifier info is provided, personal identifier type is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPersonalIdType(ApiCustomerPost.java:558)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPersonalIdType -->
  <testcase name="apiErrorBlankPhoneNumber" time="0.046" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If phone is provided, phone number is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If phone is provided, phone number is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneNumber(ApiCustomerPost.java:342)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPhoneNumber -->
  <testcase name="apiErrorBlankPhoneNumber2" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneNumber2(ApiCustomerPost.java:387)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPhoneNumber2 -->
  <testcase name="apiErrorBlankPhoneNumber3" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 2, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneNumber3(ApiCustomerPost.java:435)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPhoneNumber3 -->
  <testcase name="apiErrorBlankPhoneType" time="0.031" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If phone1 is provided, phone type is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If phone1 is provided, phone type is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneType(ApiCustomerPost.java:366)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPhoneType -->
  <testcase name="apiErrorBlankPhoneType2" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneType2(ApiCustomerPost.java:411)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPhoneType2 -->
  <testcase name="apiErrorBlankPhoneType3" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 2, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneType3(ApiCustomerPost.java:459)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPhoneType3 -->
  <testcase name="apiErrorBlankPostalCode" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If address is provided, postal code is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If address is provided, postal code is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPostalCode(ApiCustomerPost.java:318)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankPostalCode -->
  <testcase name="apiErrorBlankState" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [If address is provided, state is required.] but found [Field is blank.]">
      <![CDATA[java.lang.AssertionError: expected [If address is provided, state is required.] but found [Field is blank.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorBlankState(ApiCustomerPost.java:295)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorBlankState -->
  <testcase name="apiErrorBlankUserName" time="0.015" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorContainConsecutiveCharacterPin" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorContainConsecutiveCharacterPin(ApiCustomerPost.java:781)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorContainConsecutiveCharacterPin -->
  <testcase name="apiErrorContainContigousCharacterPin" time="0.046" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorContainContigousCharacterPin(ApiCustomerPost.java:793)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorContainContigousCharacterPin -->
  <testcase name="apiErrorContainDictionaryPassword" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorContainDictionaryPassword(ApiCustomerPost.java:756)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorContainDictionaryPassword -->
  <testcase name="apiErrorContainDigitsPassword" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorContainDigitsPassword(ApiCustomerPost.java:708)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorContainDigitsPassword -->
  <testcase name="apiErrorContainLettersPassword" time="0.032" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [errors.password.must.contain.atleast.chars] but found [errors.password.cannot.contain.contiguous.chars]">
      <![CDATA[java.lang.AssertionError: expected [errors.password.must.contain.atleast.chars] but found [errors.password.cannot.contain.contiguous.chars]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorContainLettersPassword(ApiCustomerPost.java:732)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorContainLettersPassword -->
  <testcase name="apiErrorContainSameCharacterPassword" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [errors.password.cannot.contain.same.char.consecutively] but found [errors.password.cannot.contain.contiguous.chars]">
      <![CDATA[java.lang.AssertionError: expected [errors.password.cannot.contain.same.char.consecutively] but found [errors.password.cannot.contain.contiguous.chars]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorContainSameCharacterPassword(ApiCustomerPost.java:672)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorContainSameCharacterPassword -->
  <testcase name="apiErrorContainSpecialCharactersPassword" time="0.046" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorContainSpecialCharactersPassword(ApiCustomerPost.java:744)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorContainSpecialCharactersPassword -->
  <testcase name="apiErrorContainUsernamePassword" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Password can not contain username in it.] but found [{errors.password.cannot.contain.username}]">
      <![CDATA[java.lang.AssertionError: expected [Password can not contain username in it.] but found [{errors.password.cannot.contain.username}]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorContainUsernamePassword(ApiCustomerPost.java:659)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorContainUsernamePassword -->
  <testcase name="apiErrorContainUsernamePin" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorDuplicateUserName" time="0.109" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Value already exists] but found [null]">
      <![CDATA[java.lang.AssertionError: expected [Value already exists] but found [null]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorDuplicateUserName(ApiCustomerPost.java:636)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorDuplicateUserName -->
  <testcase name="apiErrorInvalidContactType" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Invalid contact type.] but found [Invalid value.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid contact type.] but found [Invalid value.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidContactType(ApiCustomerPost.java:93)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidContactType -->
  <testcase name="apiErrorInvalidCountry" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Invalid country.] but found [Invalid value.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid country.] but found [Invalid value.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidCountry(ApiCustomerPost.java:284)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidCountry -->
  <testcase name="apiErrorInvalidCustomerType" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Invalid customer type.] but found [Invalid value.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid customer type.] but found [Invalid value.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidCustomerType(ApiCustomerPost.java:72)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidCustomerType -->
  <testcase name="apiErrorInvalidFormatEmail" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorInvalidPersonalIdType" time="0.015" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Invalid personal identifier type.] but found [Invalid value.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid personal identifier type.] but found [Invalid value.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPersonalIdType(ApiCustomerPost.java:570)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidPersonalIdType -->
  <testcase name="apiErrorInvalidPhoneNumber" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Invalid phone number.] but found [Invalid format dictated by country.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid phone number.] but found [Invalid format dictated by country.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneNumber(ApiCustomerPost.java:354)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidPhoneNumber -->
  <testcase name="apiErrorInvalidPhoneNumber2" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneNumber2(ApiCustomerPost.java:399)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidPhoneNumber2 -->
  <testcase name="apiErrorInvalidPhoneNumber3" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 2, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneNumber3(ApiCustomerPost.java:447)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidPhoneNumber3 -->
  <testcase name="apiErrorInvalidPhoneType" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Invalid phone type.] but found [Invalid value.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid phone type.] but found [Invalid value.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneType(ApiCustomerPost.java:378)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidPhoneType -->
  <testcase name="apiErrorInvalidPhoneType2" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 1, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneType2(ApiCustomerPost.java:423)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidPhoneType2 -->
  <testcase name="apiErrorInvalidPhoneType3" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.IndexOutOfBoundsException" message="Index: 2, Size: 1">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 2, Size: 1
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneType3(ApiCustomerPost.java:471)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidPhoneType3 -->
  <testcase name="apiErrorInvalidPostalCode" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorInvalidState" time="0.062" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Invalid state.] but found [Invalid value.]">
      <![CDATA[java.lang.AssertionError: expected [Invalid state.] but found [Invalid value.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidState(ApiCustomerPost.java:307)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidState -->
  <testcase name="apiErrorInvalidSuffixId" time="0.046" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidSuffixId(ApiCustomerPost.java:186)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidSuffixId -->
  <testcase name="apiErrorInvalidUserName" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [errors.general.email.invalid.format.] but found [errors.general.email.invalid.format]">
      <![CDATA[java.lang.AssertionError: expected [errors.general.email.invalid.format.] but found [errors.general.email.invalid.format]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidUserName(ApiCustomerPost.java:617)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorInvalidUserName -->
  <testcase name="apiErrorMaxLengthAddress" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorMaxLengthAddress2" time="0.015" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorMaxLengthCity" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorMaxLengthContactFirstName" time="0.063" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorMaxLengthContactLastName" time="0.031" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorMaxLengthContactMiddleName" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorMaxLengthPassword" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException" message="Unrecognized field &amp;quot;params&amp;quot; (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , &amp;quot;uid&amp;quot;, &amp;quot;fieldName&amp;quot;, &amp;quot;errorKey&amp;quot;, &amp;quot;result&amp;quot;, &amp;quot;errorMessage&amp;quot;])
 at [Source: java.io.StringReader@7c28c1; line: 1, column: 207] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse[&amp;quot;hdr&amp;quot;]-&amp;gt;automationFramework.TestCases.RestResponseHeader[&amp;quot;params&amp;quot;])">
      <![CDATA[com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "params" (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , "uid", "fieldName", "errorKey", "result", "errorMessage"])
 at [Source: java.io.StringReader@7c28c1; line: 1, column: 207] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse["hdr"]->automationFramework.TestCases.RestResponseHeader["params"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)
	at com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)
	at com.jayway.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:43)
	at com.jayway.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
	at com.jayway.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:60)
	at com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)
	at com.jayway.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:202)
	at com.jayway.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)
	at com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:55)
	at com.jayway.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:216)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:159)
	at automationFramework.TestCases.ApiCustomerPost.sendAPIRequest(ApiCustomerPost.java:972)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorMaxLengthPassword(ApiCustomerPost.java:695)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorMaxLengthPassword -->
  <testcase name="apiErrorMaxLengthPersonalId" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorMaxLengthUserName" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [errors.general.value.toolong] but found [errors.general.email.invalid.format]">
      <![CDATA[java.lang.AssertionError: expected [errors.general.value.toolong] but found [errors.general.email.invalid.format]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorMaxLengthUserName(ApiCustomerPost.java:593)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorMaxLengthUserName -->
  <testcase name="apiErrorMaximumLengthEmail" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorMaximumLengthEmail(ApiCustomerPost.java:498)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorMaximumLengthEmail -->
  <testcase name="apiErrorMinLengthPassword" time="0.031" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException" message="Unrecognized field &amp;quot;params&amp;quot; (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , &amp;quot;uid&amp;quot;, &amp;quot;fieldName&amp;quot;, &amp;quot;errorKey&amp;quot;, &amp;quot;result&amp;quot;, &amp;quot;errorMessage&amp;quot;])
 at [Source: java.io.StringReader@6bcbf05b; line: 1, column: 185] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse[&amp;quot;hdr&amp;quot;]-&amp;gt;automationFramework.TestCases.RestResponseHeader[&amp;quot;params&amp;quot;])">
      <![CDATA[com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "params" (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , "uid", "fieldName", "errorKey", "result", "errorMessage"])
 at [Source: java.io.StringReader@6bcbf05b; line: 1, column: 185] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse["hdr"]->automationFramework.TestCases.RestResponseHeader["params"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)
	at com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)
	at com.jayway.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:43)
	at com.jayway.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
	at com.jayway.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:60)
	at com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)
	at com.jayway.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:202)
	at com.jayway.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)
	at com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:55)
	at com.jayway.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:216)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:159)
	at automationFramework.TestCases.ApiCustomerPost.sendAPIRequest(ApiCustomerPost.java:972)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorMinLengthPassword(ApiCustomerPost.java:683)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorMinLengthPassword -->
  <testcase name="apiErrorMixCasesPassword" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorMixCasesPassword(ApiCustomerPost.java:720)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorMixCasesPassword -->
  <testcase name="apiErrorNonNumericPin" time="0.047" classname="automationFramework.TestCases.ApiCustomerPost"/>
  <testcase name="apiErrorSecurityAnswerBlank" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.apiErrorSecurityAnswerBlank(ApiCustomerPost.java:862)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorSecurityAnswerBlank -->
  <testcase name="apiErrorSecurityAnswerMaxLength" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.apiErrorSecurityAnswerMaxLength(ApiCustomerPost.java:874)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorSecurityAnswerMaxLength -->
  <testcase name="apiErrorSecurityQuestionBlank" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.apiErrorSecurityQuestionBlank(ApiCustomerPost.java:838)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorSecurityQuestionBlank -->
  <testcase name="apiErrorSecurityQuestionInvalid" time="0.0" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at automationFramework.TestCases.ApiCustomerPost.apiErrorSecurityQuestionInvalid(ApiCustomerPost.java:850)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorSecurityQuestionInvalid -->
  <testcase name="apiErrorSpecialCharactersEmail" time="0.031" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Cannot start with special characters: &amp;quot;.&amp;quot; ,&amp;quot;@&amp;quot; or &amp;quot;www.&amp;quot;] but found [Email cannot start with special characters.]">
      <![CDATA[java.lang.AssertionError: expected [Cannot start with special characters: "." ,"@" or "www."] but found [Email cannot start with special characters.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorSpecialCharactersEmail(ApiCustomerPost.java:510)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorSpecialCharactersEmail -->
  <testcase name="apiErrorSpecialCharactersUserName" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="java.lang.AssertionError" message="expected [Cannot start with special characters: &amp;quot;.&amp;quot; ,&amp;quot;@&amp;quot; or &amp;quot;www.&amp;quot;] but found [Email cannot start with special characters.]">
      <![CDATA[java.lang.AssertionError: expected [Cannot start with special characters: "." ,"@" or "www."] but found [Email cannot start with special characters.]
	at automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorSpecialCharactersUserName(ApiCustomerPost.java:605)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorSpecialCharactersUserName -->
  <testcase name="apiErrorTooLongPin" time="0.016" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException" message="Unrecognized field &amp;quot;params&amp;quot; (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , &amp;quot;uid&amp;quot;, &amp;quot;fieldName&amp;quot;, &amp;quot;errorKey&amp;quot;, &amp;quot;result&amp;quot;, &amp;quot;errorMessage&amp;quot;])
 at [Source: java.io.StringReader@5ca1f591; line: 1, column: 180] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse[&amp;quot;hdr&amp;quot;]-&amp;gt;automationFramework.TestCases.RestResponseHeader[&amp;quot;params&amp;quot;])">
      <![CDATA[com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "params" (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , "uid", "fieldName", "errorKey", "result", "errorMessage"])
 at [Source: java.io.StringReader@5ca1f591; line: 1, column: 180] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse["hdr"]->automationFramework.TestCases.RestResponseHeader["params"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)
	at com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)
	at com.jayway.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:43)
	at com.jayway.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
	at com.jayway.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:60)
	at com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)
	at com.jayway.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:202)
	at com.jayway.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)
	at com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:55)
	at com.jayway.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:216)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:159)
	at automationFramework.TestCases.ApiCustomerPost.sendAPIRequest(ApiCustomerPost.java:972)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorTooLongPin(ApiCustomerPost.java:816)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorTooLongPin -->
  <testcase name="apiErrorTooSmallPin" time="0.015" classname="automationFramework.TestCases.ApiCustomerPost">
    <failure type="com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException" message="Unrecognized field &amp;quot;params&amp;quot; (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , &amp;quot;uid&amp;quot;, &amp;quot;fieldName&amp;quot;, &amp;quot;errorKey&amp;quot;, &amp;quot;result&amp;quot;, &amp;quot;errorMessage&amp;quot;])
 at [Source: java.io.StringReader@777c350f; line: 1, column: 180] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse[&amp;quot;hdr&amp;quot;]-&amp;gt;automationFramework.TestCases.RestResponseHeader[&amp;quot;params&amp;quot;])">
      <![CDATA[com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "params" (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , "uid", "fieldName", "errorKey", "result", "errorMessage"])
 at [Source: java.io.StringReader@777c350f; line: 1, column: 180] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse["hdr"]->automationFramework.TestCases.RestResponseHeader["params"])
	at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)
	at com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
	at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)
	at com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)
	at com.jayway.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:43)
	at com.jayway.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)
	at com.jayway.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:60)
	at com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)
	at com.jayway.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:202)
	at com.jayway.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)
	at com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:55)
	at com.jayway.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:216)
	at com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:159)
	at automationFramework.TestCases.ApiCustomerPost.sendAPIRequest(ApiCustomerPost.java:972)
	at automationFramework.TestCases.ApiCustomerPost.apiErrorTooSmallPin(ApiCustomerPost.java:804)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- apiErrorTooSmallPin -->
  <testcase name="apiPostSuccess" time="0.063" classname="automationFramework.TestCases.ApiCustomerPost"/>
</testsuite> <!-- ApiTest -->
